language: python
python:
  - "3.6"

services:
  - postgresql

env:
  - DJANGO=2.2.5 DB=postgres

before_install:
  - export DJANGO_SETTINGS_MODULE=ifs4205team1.config.settings.testing

# install dependencies
install:
  - pip install -r requirements.txt

# setup test database
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test_user';" -U postgres

# run tests
script:
  - python manage.py test