# Generated by Django 2.2.5 on 2019-10-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcher',
            old_name='gall_vid',
            new_name='gait_vid',
        ),
        migrations.RenameField(
            model_name='researcher',
            old_name='ultra_img',
            new_name='ultrasound_img',
        ),
        migrations.AlterField(
            model_name='healthcare',
            name='license',
            field=models.CharField(max_length=16),
        ),
    ]
