# Generated by Django 2.2.5 on 2019-09-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcare',
            name='patients',
            field=models.ManyToManyField(to='core.Patient'),
        ),
    ]
