# Generated by Django 2.2.5 on 2019-10-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191002_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcare',
            name='patients',
            field=models.ManyToManyField(related_name='healthcare_patients', to='core.Patient'),
        ),
    ]
