# Generated by Django 2.2.5 on 2019-10-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191003_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcher',
            old_name='bp_read',
            new_name='bp_reading',
        ),
        migrations.RenameField(
            model_name='researcher',
            old_name='diabetes',
            new_name='gastroscope_vid',
        ),
        migrations.RenameField(
            model_name='researcher',
            old_name='hr_read',
            new_name='hr_reading',
        ),
        migrations.RenameField(
            model_name='researcher',
            old_name='temp_read',
            new_name='temp_reading',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='postalcode',
            field=models.CharField(max_length=6),
        ),
    ]
