# Generated by Django 2.2.6 on 2019-10-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191024_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='android_id_hash',
            new_name='hashed_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='device_id_hash',
            new_name='hashed_last_six',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sub_id_hash',
            new_name='latest_nonce',
        ),
        migrations.AddField(
            model_name='user',
            name='nonce_timestamp',
            field=models.DateTimeField(default=None, blank=True, null=True),
        ),
    ]
