# Generated by Django 2.2.6 on 2019-11-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191029_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip1',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ip2',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ip3',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ip4',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ip5',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ip6',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='latest_nonce2',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='login1',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login2',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login3',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login4',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login5',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login6',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nonce2_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='latest_nonce',
            field=models.CharField(default='', max_length=64),
        ),
    ]
