# Generated by Django 2.2.6 on 2019-11-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191101_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loginattempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
