# Generated by Django 2.2.6 on 2019-11-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_loginattempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
