# Generated by Django 2.2.6 on 2019-11-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lockedipaddr',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
    ]
