# Generated by Django 2.2.6 on 2019-11-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191103_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='locked',
            name='lockeduser',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
