# Generated by Django 2.2.6 on 2019-11-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_locked_lockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interface',
            field=models.CharField(blank=True, null=True, default=None, max_length=11),
        ),
    ]
