# Generated by Django 2.2.5 on 2019-09-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='data',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='data',
            field=models.FileField(upload_to='timeseries/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='data',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
