# Generated by Django 2.2.5 on 2019-09-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingsperm',
            name='perm_value',
            field=models.PositiveSmallIntegerField(choices=[('1', 'No Access'), ('2', 'Read Only Access'), ('3', 'Read & Set Permissions Access'), ('4', 'Owner')]),
        ),
    ]
