# Generated by Django 2.2.5 on 2019-09-10 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='img',
            new_name='img_hash',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='video',
            new_name='video_hash',
        ),
    ]
