# Generated by Django 2.2.5 on 2019-10-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0002_auto_20190930_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readings',
            name='data',
            field=models.CharField(max_length=15),
        ),
    ]
