# Generated by Django 2.2.5 on 2019-09-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0003_auto_20190910_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='content',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='img_hash',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='readings',
            old_name='value',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='video_hash',
            new_name='data',
        ),
    ]
