# Generated by Django 2.2.5 on 2019-10-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0004_auto_20191002_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
    ]
