# Generated by Django 2.2.5 on 2019-10-03 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0006_auto_20191003_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisperm',
            name='username',
            field=models.ManyToManyField(to='core.Healthcare'),
        ),
        migrations.AlterField(
            model_name='documentsperm',
            name='username',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagesperm',
            name='username',
            field=models.ManyToManyField(to='core.Healthcare'),
        ),
        migrations.AlterField(
            model_name='readingsperm',
            name='username',
            field=models.ManyToManyField(to='core.Healthcare'),
        ),
        migrations.AlterField(
            model_name='timeseriesperm',
            name='username',
            field=models.ManyToManyField(to='core.Healthcare'),
        ),
        migrations.AlterField(
            model_name='videosperm',
            name='username',
            field=models.ManyToManyField(to='core.Healthcare'),
        ),
    ]
