# Generated by Django 2.2.5 on 2019-10-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0008_auto_20191025_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='attach_documents',
            field=models.ManyToManyField(related_name='_documents_attach_documents_+', to='patientrecords.Documents'),
        ),
        migrations.AddField(
            model_name='documents',
            name='attach_images',
            field=models.ManyToManyField(to='patientrecords.Images'),
        ),
        migrations.AddField(
            model_name='documents',
            name='attach_readings',
            field=models.ManyToManyField(to='patientrecords.Readings'),
        ),
        migrations.AddField(
            model_name='documents',
            name='attach_timeseries',
            field=models.ManyToManyField(to='patientrecords.TimeSeries'),
        ),
        migrations.AddField(
            model_name='documents',
            name='attach_videos',
            field=models.ManyToManyField(to='patientrecords.Videos'),
        ),
    ]
