# Generated by Django 2.2.6 on 2019-10-28 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191028_1754'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patientrecords', '0009_auto_20191026_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='username',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_patient', to='core.Patient'),
            preserve_default=False,
        ),
    ]
