# Generated by Django 2.2.6 on 2019-10-29 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20191029_2141'),
        ('patientrecords', '0010_auto_20191029_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField()),
                ('content', models.CharField(max_length=64)),
                ('status', models.BooleanField(default=True)),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications_from', to=settings.AUTH_USER_MODEL)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_patient', to='core.Patient')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications_to', to='core.Healthcare')),
            ],
        ),
    ]
