# Generated by Django 2.2.6 on 2019-10-31 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0011_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='from_id',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='to_id',
            new_name='to_healthcare',
        ),
    ]
