# Generated by Django 2.2.6 on 2019-10-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0012_auto_20191031_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
