# Generated by Django 2.2.6 on 2019-11-01 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecords', '0014_auto_20191031_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='data',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
    ]
