# Generated by Django 2.2.5 on 2019-10-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcherquery', '0002_auto_20191019_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safeimages',
            name='type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='safereadings',
            name='type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='safevideos',
            name='type',
            field=models.CharField(max_length=64),
        ),
    ]
