# Generated by Django 2.2.6 on 2019-11-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcherquery', '0003_auto_20191027_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safeusers',
            name='uid',
        ),
        migrations.AddField(
            model_name='safeusers',
            name='id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
