# Generated by Django 2.2.6 on 2019-11-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researcherquery', '0004_auto_20191106_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safediagnosis',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='safeimages',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='safereadings',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='safevideos',
            name='uid',
        ),
    ]
