# Generated by Django 2.2.6 on 2019-11-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researcherquery', '0005_auto_20191107_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='safediagnosis',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='researcherquery.SafeUsers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safeimages',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='researcherquery.SafeUsers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safereadings',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='researcherquery.SafeUsers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safevideos',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='researcherquery.SafeUsers'),
            preserve_default=False,
        ),
    ]
