# Generated by Django 2.2.5 on 2019-10-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='interface',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='status',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
