"""
Django settings for ifs4205team1 project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from os.path import join, dirname
from dotenv import load_dotenv

from qr_code.qrcode import constants

from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

# Load environment variables
dotenv_path = os.path.join(BASE_DIR, 'ifs4205team1', 'config', 'settings', '.env')
load_dotenv(dotenv_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # THIRD-PARTY APPS
    'bleach',
    'django_bleach',
    'widget_tweaks',
    'django_select2',
    'qr_code',
    'axes',

  	# APPS
    'ifs4205team1',
  	'core',
    'adminlogin',
    'adminusers',
    'patientlogin',
    'patientrecords',
    'patienthealthcare',
    'healthcarelogin',
    'healthcarepatients',
    'healthcarenotes',
    'researcherlogin',
    'researcherquery',
    'mobileregister',
    'userlogs',
]

# Extending User Model

AUTH_USER_MODEL = 'core.User'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    # Default Django authentication backend
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'ifs4205team1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ifs4205team1.wsgi.application'

SESSION_EXPIRE_SECONDS = 5*60  # 5 mins
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True # Expires after 5 minutes of inactivity

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password Hashing Algorithm

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
	os.path.join(BASE_DIR, "static"),
    '/adminlogin/static',
	'/researcherquery/static',
]

# Media Files

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

PROTECTED_MEDIA_URL = os.environ.get("PROTECTED_MEDIA_URL")
PROTECTED_MEDIA_PATH = os.environ.get("PROTECTED_MEDIA_PATH")

RESEARCHER_IMAGE_URL = os.environ.get("RESEARCHER_IMAGE_URL")
RESEARCHER_IMAGE_PATH = os.environ.get("RESEARCHER_IMAGE_PATH")

RESEARCHER_VIDEO_URL = os.environ.get("RESEARCHER_VIDEO_URL")
RESEARCHER_VIDEO_PATH = os.environ.get("RESEARCHER_VIDEO_PATH")

# Admin Page
ADMIN_URL = os.environ.get("ADMIN_URL")

# Server

HOSTED_SITE_URL = 'https://ifs4205team1-3.comp.nus.edu.sg'

# Axes Configuration
AXES_FAILURE_LIMIT = 100000
# AXES_ONLY_USER_FAILURES = True